### ISSUE TITLE
XML Files

### ISSUE THREAD

**Issue by sqrlmstr5000** [larsch/eclipse-linecopypaste#1]
Is the plugin meant to work in XML files. It works great in Java files but it's not working on other types like XML. Other than that great plugin!

**Comment by larsch** [comment]
I don't have that problem here - it works for me in any file type I have tried. Which editor are you using for XML files? (I've tried with the Eclipse XML Editors v. 3.2.2). You can also check if the bindings are set up correctly in XML mode. Sometimes, other defaults may override the linecopypaste defaults and.

**Comment by sqrlmstr5000** [comment]
I'm using it with Eclipse 3.6.2 for Android development. When I open an xml file it kills all the Ctrl+C commands, they are still listed in the Key bindings tho.
